version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bisnesmedia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5433:5432"
    restart: always

  app:
    build: .
    container_name: bisnesmedia_app
    env_file:
      - .env
    ports:
      - "8000:80"
    depends_on:
      - db
    restart: always

  admin_panel:
    build:
      context: .
      dockerfile: Dockerfile.admin
    container_name: bisnesmedia_admin
    env_file:
      - .env
    environment:
      - ADMIN_DB_URL=${ADMIN_DB_URL}
      - ADMIN_APP_URL=${ADMIN_APP_URL}
      - ADMIN_POLL_SECONDS=${ADMIN_POLL_SECONDS:-5}
      - ADMIN_PAGE_SIZE=${ADMIN_PAGE_SIZE:-500}
    ports:
      - "8501:8501"
    depends_on:
      - app
      - db
    restart: always

volumes:
  postgres_data:

