services:
  db:
    image: postgres:15
    container_name: bisnesmedia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bisnesmedia/app:dev  # <--- ВОТ ЭТА СТРОКА
    container_name: bisnesmedia_app
    # command убран — запуск через start.sh из Dockerfile
    volumes:
      - ./app:/app/app
      - ./prestart.py:/app/prestart.py
      - ./start.sh:/app/start.sh
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  admin_panel:
    build:
      context: .
      dockerfile: Dockerfile.admin
    image: bisnesmedia/admin:dev # <--- И ВОТ ЭТА СТРОКА
    container_name: bisnesmedia_admin
    # Убираем задержку и упрощаем команду запуска
    command: ./.venv/bin/python -m streamlit run admin_panel/app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - ./admin_panel:/app/admin_panel
      - ./app:/app/app
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - app
      - db

volumes:
  postgres_data:
