"""add job_name to integration_logs

Revision ID: 20250923113000
Revises: 20250923093000
Create Date: 2025-09-23 11:30:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "20250923113000"
down_revision = "20250923093000"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before adding it
    connection = op.get_bind()
    result = connection.execute(sa.text("""
        SELECT column_name
        FROM information_schema.columns
        WHERE table_name='integration_logs' AND column_name='job_name'
    """))
    if not result.fetchone():
        op.add_column("integration_logs", sa.Column("job_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("integration_logs", "job_name")
    # ### end Alembic commands ###